name: Build ALE Python

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build ALE Python on ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        config: [
          {"os": "ubuntu-latest", "deps": ["zlib", "sdl2"], "triplet": "x64-linux-mixed"},
          {"os": "windows-latest", "deps": ["zlib", "sdl2"], "triplet": "x64-windows"},
          {"os": "macos-latest", "deps": ["zlib", "sdl2"], "triplet": "x64-osx-mixed"}
        ]
    steps:
    - uses: actions/checkout@v2

    - name: Docker Login
      if: matrix.config.os == 'ubuntu-latest'
      run: docker login ghcr.io --username "${GITHUB_ACTOR}" --password "${GITHUB_CR_TOKEN}"
      env:
        GITHUB_CR_TOKEN: ${{ secrets.CR_TOKEN }}

    - uses: actions/setup-python@v1
      name: Install Python
      with:
        python-version: "3.9"

    - name: "Tag release"
      run: echo "ALE_BUILD_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

    - name: "Update vcpkg repository"
      run: |
        git -C "$VCPKG_INSTALLATION_ROOT" fetch
        git -C "$VCPKG_INSTALLATION_ROOT" reset --hard origin/master

    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel==1.7.2

    - name: Build wheels
      run: |
        python -m cibuildwheel --output-dir wheelhouse
      env:
        CIBW_MANYLINUX_X86_64_IMAGE: "ghcr.io/jessefarebro/manylinux2014"
        CIBW_BUILD: "cp3[6789]-*"
        CIBW_SKIP: "*i686* *win32* cp36-win* cp37-win*"
        CIBW_TEST_REQUIRES: "pytest"
        CIBW_TEST_COMMAND: "pytest {project}"
        CIBW_ENVIRONMENT: "VCPKG_DEFAULT_TRIPLET=${{ matrix.config.triplet }} MACOSX_DEPLOYMENT_TARGET='10.9' ALE_BUILD_VERSION=${{ env.ALE_BUILD_VERSION }}"
        CIBW_BEFORE_ALL: "vcpkg install ${{ join(matrix.config.deps, ' ') }} --triplet ${{ matrix.config.triplet }} --overlay-triplets cmake/custom-triplets --feature-flags=-compilertracking"
    - uses: actions/upload-artifact@v1
      with:
        name: wheels
        path: wheelhouse


  pypi:
    name: Deploy ALE Python to PyPi test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: wheels

      - name: Append PyPi test SHA 
        run: |
          find wheels -type f -exec sh -c \
            "mv {} \$(echo {} | awk -F\"-\" '{OFS = FS; \$2 = \$2\"+${GITHUB_SHA::7}\"; print}')" \;

      - name: Publish to PyPi test
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_test_token }}
          repository_url: https://test.pypi.org/legacy/
          packages_dir: wheels/


  release:
    name: Stage ALE Python to Github releases
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: wheels

      - name: Create wheel archive
        run: |
          zip --junk-paths ale-py wheels/*

      - name: Create release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: ${{ contains(github.ref, '-') }}

      - name: Upload artifacts to release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ale-py.zip
          asset_name: ale-py.zip
          asset_content_type: application/zip
