name: Build ALE

on:
  push:
    tags-ignore:
      - "*.*"
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  presubmit:
    name: Presubmit checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./scripts/presubmit.sh

  build:
    name: Build ALE on ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    needs: presubmit
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        config: [
          {"os": "ubuntu-latest", "deps": ["zlib", "sdl2"], "triplet": "x64-linux-mixed"},
          {"os": "windows-latest", "deps": ["zlib", "sdl2"], "triplet": "x64-windows"},
          {"os": "macos-latest", "deps": ["zlib", "sdl2"], "triplet": "x64-osx-mixed"}
        ]
    env:
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.config.triplet }}
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install numpy pytest cmake
        git -C "$VCPKG_INSTALLATION_ROOT" fetch
        git -C "$VCPKG_INSTALLATION_ROOT" reset --hard origin/master
        vcpkg install ${{ join(matrix.config.deps, ' ') }} --triplet ${{ matrix.config.triplet }} --overlay-triplets cmake/custom-triplets

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ${{ env.VCPKG_INSTALLATION_ROOT }}/installed
        key: ${{ matrix.config.os }}--vcpkg--${{ hashFiles(format('{0}/.git', env.VCPKG_INSTALLATION_ROOT)) }}

    - name: Configure ALE
      run: |
        mkdir build; cd build
        cmake ../ -DSDL_SUPPORT=ON -DPython3_FIND_FRAMEWORK=NEVER

    - name: Build ALE
      working-directory: ./build
      run: cmake --build . --config Debug --parallel 2

    - name: Test ALE
      working-directory: ./build
      run: ctest -C Debug --progress -VV
